services:
  server:
    build:
      context: .
      target: base
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 3001:3001
      - 9229:9229 # inspect port
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
    volumes:
      - ./:/app
      # - ./.env:/app/.env
      # - ./.env.test:/app/.env.test
      # - ./.sequelizerc:/app/.sequelizerc
      # - ./storage:/app/storage
      - /app/node_modules
    command: npm run dev
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt